Emoticons = {
	'GRINNING FACE': b'\xf0\x9f\x98\x80'.decode("utf8"),
	'GRINNING FACE WITH SMILING EYES': b'\xf0\x9f\x98\x81'.decode("utf8"),
	'FACE WITH TEARS OF JOY': b'\xf0\x9f\x98\x82'.decode("utf8"),
	'SMILING FACE WITH OPEN MOUTH': b'\xf0\x9f\x98\x83'.decode("utf8"),
	'SMILING FACE WITH OPEN MOUTH AND SMILING EYES': b'\xf0\x9f\x98\x84'.decode("utf8"),
	'SMILING FACE WITH OPEN MOUTH AND COLD SWEAT': b'\xf0\x9f\x98\x85'.decode("utf8"),
	'SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES': b'\xf0\x9f\x98\x86'.decode("utf8"),
	'SMILING FACE WITH HALO': b'\xf0\x9f\x98\x87'.decode("utf8"),
	'SMILING FACE WITH HORNS': b'\xf0\x9f\x98\x88'.decode("utf8"),
	'WINKING FACE': b'\xf0\x9f\x98\x89'.decode("utf8"),
	'SMILING FACE WITH SMILING EYES': b'\xf0\x9f\x98\x8a'.decode("utf8"),
	'FACE SAVOURING DELICIOUS FOOD': b'\xf0\x9f\x98\x8b'.decode("utf8"),
	'RELIEVED FACE': b'\xf0\x9f\x98\x8c'.decode("utf8"),
	'SMILING FACE WITH HEART-SHAPED EYES': b'\xf0\x9f\x98\x8d'.decode("utf8"),
	'SMILING FACE WITH SUNGLASSES': b'\xf0\x9f\x98\x8e'.decode("utf8"),
	'SMIRKING FACE': b'\xf0\x9f\x98\x8f'.decode("utf8"),
	'NEUTRAL FACE': b'\xf0\x9f\x98\x90'.decode("utf8"),
	'EXPRESSIONLESS FACE': b'\xf0\x9f\x98\x91'.decode("utf8"),
	'UNAMUSED FACE': b'\xf0\x9f\x98\x92'.decode("utf8"),
	'FACE WITH COLD SWEAT': b'\xf0\x9f\x98\x93'.decode("utf8"),
	'PENSIVE FACE': b'\xf0\x9f\x98\x94'.decode("utf8"),
	'CONFUSED FACE': b'\xf0\x9f\x98\x95'.decode("utf8"),
	'CONFOUNDED FACE': b'\xf0\x9f\x98\x96'.decode("utf8"),
	'KISSING FACE': b'\xf0\x9f\x98\x97'.decode("utf8"),
	'FACE THROWING A KISS': b'\xf0\x9f\x98\x98'.decode("utf8"),
	'KISSING FACE WITH SMILING EYES': b'\xf0\x9f\x98\x99'.decode("utf8"),
	'KISSING FACE WITH CLOSED EYES': b'\xf0\x9f\x98\x9a'.decode("utf8"),
	'FACE WITH STUCK-OUT TONGUE': b'\xf0\x9f\x98\x9b'.decode("utf8"),
	'FACE WITH STUCK-OUT TONGUE AND WINKING EYE': b'\xf0\x9f\x98\x9c'.decode("utf8"),
	'FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES': b'\xf0\x9f\x98\x9d'.decode("utf8"),
	'DISAPPOINTED FACE': b'\xf0\x9f\x98\x9e'.decode("utf8"),
	'WORRIED FACE': b'\xf0\x9f\x98\x9f'.decode("utf8"),
	'ANGRY FACE': b'\xf0\x9f\x98\xa0'.decode("utf8"),
	'POUTING FACE': b'\xf0\x9f\x98\xa1'.decode("utf8"),
	'CRYING FACE': b'\xf0\x9f\x98\xa2'.decode("utf8"),
	'PERSEVERING FACE': b'\xf0\x9f\x98\xa3'.decode("utf8"),
	'FACE WITH LOOK OF TRIUMPH': b'\xf0\x9f\x98\xa4'.decode("utf8"),
	'DISAPPOINTED BUT RELIEVED FACE': b'\xf0\x9f\x98\xa5'.decode("utf8"),
	'FROWNING FACE WITH OPEN MOUTH': b'\xf0\x9f\x98\xa6'.decode("utf8"),
	'ANGUISHED FACE': b'\xf0\x9f\x98\xa7'.decode("utf8"),
	'FEARFUL FACE': b'\xf0\x9f\x98\xa8'.decode("utf8"),
	'WEARY FACE': b'\xf0\x9f\x98\xa9'.decode("utf8"),
	'SLEEPY FACE': b'\xf0\x9f\x98\xaa'.decode("utf8"),
	'TIRED FACE': b'\xf0\x9f\x98\xab'.decode("utf8"),
	'GRIMACING FACE': b'\xf0\x9f\x98\xac'.decode("utf8"),
	'LOUDLY CRYING FACE': b'\xf0\x9f\x98\xad'.decode("utf8"),
	'FACE WITH OPEN MOUTH': b'\xf0\x9f\x98\xae'.decode("utf8"),
	'HUSHED FACE': b'\xf0\x9f\x98\xaf'.decode("utf8"),
	'FACE WITH OPEN MOUTH AND COLD SWEAT': b'\xf0\x9f\x98\xb0'.decode("utf8"),
	'FACE SCREAMING IN FEAR': b'\xf0\x9f\x98\xb1'.decode("utf8"),
	'ASTONISHED FACE': b'\xf0\x9f\x98\xb2'.decode("utf8"),
	'FLUSHED FACE': b'\xf0\x9f\x98\xb3'.decode("utf8"),
	'SLEEPING FACE': b'\xf0\x9f\x98\xb4'.decode("utf8"),
	'DIZZY FACE': b'\xf0\x9f\x98\xb5'.decode("utf8"),
	'FACE WITHOUT MOUTH': b'\xf0\x9f\x98\xb6'.decode("utf8"),
	'FACE WITH MEDICAL MASK': b'\xf0\x9f\x98\xb7'.decode("utf8"),
	'GRINNING CAT FACE WITH SMILING EYES': b'\xf0\x9f\x98\xb8'.decode("utf8"),
	'CAT FACE WITH TEARS OF JOY': b'\xf0\x9f\x98\xb9'.decode("utf8"),
	'SMILING CAT FACE WITH OPEN MOUTH': b'\xf0\x9f\x98\xba'.decode("utf8"),
	'SMILING CAT FACE WITH HEART-SHAPED EYES': b'\xf0\x9f\x98\xbb'.decode("utf8"),
	'CAT FACE WITH WRY SMILE': b'\xf0\x9f\x98\xbc'.decode("utf8"),
	'KISSING CAT FACE WITH CLOSED EYES': b'\xf0\x9f\x98\xbd'.decode("utf8"),
	'POUTING CAT FACE': b'\xf0\x9f\x98\xbe'.decode("utf8"),
	'CRYING CAT FACE': b'\xf0\x9f\x98\xbf'.decode("utf8"),
	'WEARY CAT FACE': b'\xf0\x9f\x99\x80'.decode("utf8"),
	'SLIGHTLY FROWNING FACE': b'\xf0\x9f\x99\x81'.decode("utf8"),
	'SLIGHTLY SMILING FACE': b'\xf0\x9f\x99\x82'.decode("utf8"),
	'UPSIDE-DOWN FACE': b'\xf0\x9f\x99\x83'.decode("utf8"),
	'FACE WITH ROLLING EYES': b'\xf0\x9f\x99\x84'.decode("utf8"),
	'FACE WITH NO GOOD GESTURE': b'\xf0\x9f\x99\x85'.decode("utf8"),
	'FACE WITH OK GESTURE': b'\xf0\x9f\x99\x86'.decode("utf8"),
	'PERSON BOWING DEEPLY': b'\xf0\x9f\x99\x87'.decode("utf8"),
	'SEE-NO-EVIL MONKEY': b'\xf0\x9f\x99\x88'.decode("utf8"),
	'HEAR-NO-EVIL MONKEY': b'\xf0\x9f\x99\x89'.decode("utf8"),
	'SPEAK-NO-EVIL MONKEY': b'\xf0\x9f\x99\x8a'.decode("utf8"),
	'HAPPY PERSON RAISING ONE HAND': b'\xf0\x9f\x99\x8b'.decode("utf8"),
	'PERSON RAISING BOTH HANDS IN CELEBRATION': b'\xf0\x9f\x99\x8c'.decode("utf8"),
	'PERSON FROWNING': b'\xf0\x9f\x99\x8d'.decode("utf8"),
	'PERSON WITH POUTING FACE': b'\xf0\x9f\x99\x8e'.decode("utf8"),
	'PERSON WITH FOLDED HANDS': b'\xf0\x9f\x99\x8f'.decode("utf8"),
	'ROCKET': b'\xf0\x9f\x9a\x80'.decode("utf8"),
	'HELICOPTER': b'\xf0\x9f\x9a\x81'.decode("utf8"),
	'STEAM LOCOMOTIVE': b'\xf0\x9f\x9a\x82'.decode("utf8"),
	'RAILWAY CAR': b'\xf0\x9f\x9a\x83'.decode("utf8"),
	'HIGH-SPEED TRAIN': b'\xf0\x9f\x9a\x84'.decode("utf8"),
	'HIGH-SPEED TRAIN WITH BULLET NOSE': b'\xf0\x9f\x9a\x85'.decode("utf8"),
	'TRAIN': b'\xf0\x9f\x9a\x86'.decode("utf8"),
	'METRO': b'\xf0\x9f\x9a\x87'.decode("utf8"),
	'LIGHT RAIL': b'\xf0\x9f\x9a\x88'.decode("utf8"),
	'STATION': b'\xf0\x9f\x9a\x89'.decode("utf8"),
	'TRAM': b'\xf0\x9f\x9a\x8a'.decode("utf8"),
	'TRAM CAR': b'\xf0\x9f\x9a\x8b'.decode("utf8"),
	'BUS': b'\xf0\x9f\x9a\x8c'.decode("utf8"),
	'ONCOMING BUS': b'\xf0\x9f\x9a\x8d'.decode("utf8"),
	'TROLLEYBUS': b'\xf0\x9f\x9a\x8e'.decode("utf8"),
	'BUS STOP': b'\xf0\x9f\x9a\x8f'.decode("utf8"),
	'MINIBUS': b'\xf0\x9f\x9a\x90'.decode("utf8"),
	'AMBULANCE': b'\xf0\x9f\x9a\x91'.decode("utf8"),
	'FIRE ENGINE': b'\xf0\x9f\x9a\x92'.decode("utf8"),
	'POLICE CAR': b'\xf0\x9f\x9a\x93'.decode("utf8"),
	'ONCOMING POLICE CAR': b'\xf0\x9f\x9a\x94'.decode("utf8"),
	'TAXI': b'\xf0\x9f\x9a\x95'.decode("utf8"),
	'ONCOMING TAXI': b'\xf0\x9f\x9a\x96'.decode("utf8"),
	'AUTOMOBILE': b'\xf0\x9f\x9a\x97'.decode("utf8"),
	'ONCOMING AUTOMOBILE': b'\xf0\x9f\x9a\x98'.decode("utf8"),
	'RECREATIONAL VEHICLE': b'\xf0\x9f\x9a\x99'.decode("utf8"),
	'DELIVERY TRUCK': b'\xf0\x9f\x9a\x9a'.decode("utf8"),
	'ARTICULATED LORRY': b'\xf0\x9f\x9a\x9b'.decode("utf8"),
	'TRACTOR': b'\xf0\x9f\x9a\x9c'.decode("utf8"),
	'MONORAIL': b'\xf0\x9f\x9a\x9d'.decode("utf8"),
	'MOUNTAIN RAILWAY': b'\xf0\x9f\x9a\x9e'.decode("utf8"),
	'SUSPENSION RAILWAY': b'\xf0\x9f\x9a\x9f'.decode("utf8"),
	'MOUNTAIN CABLEWAY': b'\xf0\x9f\x9a\xa0'.decode("utf8"),
	'AERIAL TRAMWAY': b'\xf0\x9f\x9a\xa1'.decode("utf8"),
	'SHIP': b'\xf0\x9f\x9a\xa2'.decode("utf8"),
	'ROWBOAT': b'\xf0\x9f\x9a\xa3'.decode("utf8"),
	'SPEEDBOAT': b'\xf0\x9f\x9a\xa4'.decode("utf8"),
	'HORIZONTAL TRAFFIC LIGHT': b'\xf0\x9f\x9a\xa5'.decode("utf8"),
	'VERTICAL TRAFFIC LIGHT': b'\xf0\x9f\x9a\xa6'.decode("utf8"),
	'CONSTRUCTION SIGN': b'\xf0\x9f\x9a\xa7'.decode("utf8"),
	'POLICE CARS REVOLVING LIGHT': b'\xf0\x9f\x9a\xa8'.decode("utf8"),
	'TRIANGULAR FLAG ON POST': b'\xf0\x9f\x9a\xa9'.decode("utf8"),
	'DOOR': b'\xf0\x9f\x9a\xaa'.decode("utf8"),
	'NO ENTRY SIGN': b'\xf0\x9f\x9a\xab'.decode("utf8"),
	'SMOKING SYMBOL': b'\xf0\x9f\x9a\xac'.decode("utf8"),
	'NO SMOKING SYMBOL': b'\xf0\x9f\x9a\xad'.decode("utf8"),
	'PUT LITTER IN ITS PLACE SYMBOL': b'\xf0\x9f\x9a\xae'.decode("utf8"),
	'DO NOT LITTER SYMBOL': b'\xf0\x9f\x9a\xaf'.decode("utf8"),
	'POTABLE WATER SYMBOL': b'\xf0\x9f\x9a\xb0'.decode("utf8"),
	'NON-POTABLE WATER SYMBOL': b'\xf0\x9f\x9a\xb1'.decode("utf8"),
	'BICYCLE': b'\xf0\x9f\x9a\xb2'.decode("utf8"),
	'NO BICYCLES': b'\xf0\x9f\x9a\xb3'.decode("utf8"),
	'BICYCLIST': b'\xf0\x9f\x9a\xb4'.decode("utf8"),
	'MOUNTAIN BICYCLIST': b'\xf0\x9f\x9a\xb5'.decode("utf8"),
	'PEDESTRIAN': b'\xf0\x9f\x9a\xb6'.decode("utf8"),
	'NO PEDESTRIANS': b'\xf0\x9f\x9a\xb7'.decode("utf8"),
	'CHILDREN CROSSING': b'\xf0\x9f\x9a\xb8'.decode("utf8"),
	'MENS SYMBOL': b'\xf0\x9f\x9a\xb9'.decode("utf8"),
	'WOMENS SYMBOL': b'\xf0\x9f\x9a\xba'.decode("utf8"),
	'RESTROOM': b'\xf0\x9f\x9a\xbb'.decode("utf8"),
	'BABY SYMBOL': b'\xf0\x9f\x9a\xbc'.decode("utf8"),
	'TOILET': b'\xf0\x9f\x9a\xbd'.decode("utf8"),
	'WATER CLOSET': b'\xf0\x9f\x9a\xbe'.decode("utf8"),
	'SHOWER': b'\xf0\x9f\x9a\xbf'.decode("utf8"),
	'BATH': b'\xf0\x9f\x9b\x80'.decode("utf8"),
	'BATHTUB': b'\xf0\x9f\x9b\x81'.decode("utf8"),
	'PASSPORT CONTROL': b'\xf0\x9f\x9b\x82'.decode("utf8"),
	'CUSTOMS': b'\xf0\x9f\x9b\x83'.decode("utf8"),
	'BAGGAGE CLAIM': b'\xf0\x9f\x9b\x84'.decode("utf8"),
	'LEFT LUGGAGE': b'\xf0\x9f\x9b\x85'.decode("utf8"),
	'COUCH AND LAMP': b'\xf0\x9f\x9b\x8b'.decode("utf8"),
	'SLEEPING ACCOMMODATION': b'\xf0\x9f\x9b\x8c'.decode("utf8"),
	'SHOPPING BAGS': b'\xf0\x9f\x9b\x8d'.decode("utf8"),
	'BELLHOP BELL': b'\xf0\x9f\x9b\x8e'.decode("utf8"),
	'BED': b'\xf0\x9f\x9b\x8f'.decode("utf8"),
	'PLACE OF WORSHIP': b'\xf0\x9f\x9b\x90'.decode("utf8"),
	'HAMMER AND WRENCH': b'\xf0\x9f\x9b\xa0'.decode("utf8"),
	'SHIELD': b'\xf0\x9f\x9b\xa1'.decode("utf8"),
	'OIL DRUM': b'\xf0\x9f\x9b\xa2'.decode("utf8"),
	'MOTORWAY': b'\xf0\x9f\x9b\xa3'.decode("utf8"),
	'RAILWAY TRACK': b'\xf0\x9f\x9b\xa4'.decode("utf8"),
	'MOTOR BOAT': b'\xf0\x9f\x9b\xa5'.decode("utf8"),
	'SMALL AIRPLANE': b'\xf0\x9f\x9b\xa9'.decode("utf8"),
	'AIRPLANE DEPARTURE': b'\xf0\x9f\x9b\xab'.decode("utf8"),
	'AIRPLANE ARRIVING': b'\xf0\x9f\x9b\xac'.decode("utf8"),
	'SATELLITE': b'\xf0\x9f\x9b\xb0'.decode("utf8"),
	'PASSENGER SHIP': b'\xf0\x9f\x9b\xb3'.decode("utf8"),
	'ZIPPER-MOUTH FACE': b'\xf0\x9f\xa4\x90'.decode("utf8"),
	'MONEY-MOUTH FACE': b'\xf0\x9f\xa4\x91'.decode("utf8"),
	'FACE WITH THERMOMETER': b'\xf0\x9f\xa4\x92'.decode("utf8"),
	'NERD FACE': b'\xf0\x9f\xa4\x93'.decode("utf8"),
	'THINKING FACE': b'\xf0\x9f\xa4\x94'.decode("utf8"),
	'FACE WITH HEAD-BANDAGE': b'\xf0\x9f\xa4\x95'.decode("utf8"),
	'ROBOT FACE': b'\xf0\x9f\xa4\x96'.decode("utf8"),
	'HUGGING FACE': b'\xf0\x9f\xa4\x97'.decode("utf8"),
	'SIGN OF THE HORNS': b'\xf0\x9f\xa4\x98'.decode("utf8"),
	'CRAB': b'\xf0\x9f\xa6\x80'.decode("utf8"),
	'LION FACE': b'\xf0\x9f\xa6\x81'.decode("utf8"),
	'SCORPION': b'\xf0\x9f\xa6\x82'.decode("utf8"),
	'TURKEY': b'\xf0\x9f\xa6\x83'.decode("utf8"),
	'UNICORN FACE': b'\xf0\x9f\xa6\x84'.decode("utf8"),
	'CHEESE WEDGE': b'\xf0\x9f\xa7\x80'.decode("utf8")
}
